# Author : Malte Aschenbach <ma28@autistici.org>

key = { fg = "white", bg = "#011627", underline = { color = "red", style = "curl"}, modifiers = ["bold", "italic"] }

"ui.selection" ={bg = "red"}

[palette]
"black"   = "#000000"
"red"     = "#ef5350"
"green"   =  "#22da6e"
"yellow"  =  "#addb67"
"blue"    =  "#82aaff"
"magenta" =  "#c792ea"
"cyan"    =  "#21c7a8"
"white"   = "#ffffff"